---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webapp
    spec:
      restartPolicy: Always
      containers:
        - name: webapp
          image: ezhov_server
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 80
              hostPort: 8000
              protocol: TCP
          volumeMounts:
            - name: apache-initdir
              mountPath: /var/www/html
          env:
            - name: username
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: password
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: database
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: mysql-url
      volumes:
        - name: apache-initdir
          hostPath:
            path: /mnt/e/docker/src
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 30080
