---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: ezhov-server
          ports:
            - containerPort: 80
          volumeMounts:
            - name: apache-initdir
              mountPath: /var/www/html
          env:
            - name: username
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: password
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
            - name: database
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: database
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
      volumes:
        - name: apache-initdir
          hostPath:
            path: src/
            type: Directory

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 8000
